version: '3.9'

services:
  service_user_management:
    image: 121113815220.dkr.ecr.us-west-2.amazonaws.com/charging-prod-us-west-2-ecr-consumer:user-management-latest
    build:
      context: ./
      dockerfile: ./apps/user-management/Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3003:3003
    volumes:
      - .:/apps/user-management
  
  service_charging_event:
    image: 121113815220.dkr.ecr.us-west-2.amazonaws.com/charging-prod-us-west-2-ecr-consumer:charging-event-latest
    build:
      context: ./
      dockerfile: ./apps/charging-event/Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3004:3004
    volumes:
      - .:/apps/charging-event